services:
  - type: web
    name: search-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
